/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Programas;

import Grafos.ArcoPanel;
import Grafos.Dijkstra;
import Grafos.GrafoAdcia;
import Grafos.GrafoMatriz;
import Grafos.ResultadoDijkstra;
import Grafos.VerticePanel;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author crist
 */
public class Form extends javax.swing.JFrame {

    /**
     * Creates new form Form
     */
    Visualizador f;
    ArrayList<VerticePanel> vertices;
    GrafoMatriz grafoM;
    public Form() {
        initComponents(); 
        
        this.getContentPane().setBackground(new Color(240, 242, 245)); 
    
        // 1. COLORES DE FONDO UNIFICADOS
        Color azulOscuro = new Color(44, 62, 80);

        // Pinta el fondo de la ventana completa
        this.getContentPane().setBackground(azulOscuro); 

        // IMPORTANTE: Pinta el panel que contiene el título "Opciones"
        // (Truco: obtenemos el padre del Label "Opciones")
        JPanel panelTitulo = (JPanel) jLabel2.getParent();
        panelTitulo.setBackground(azulOscuro);

        // Pinta el panel de los controles
        JPanel panelControles = (JPanel) jComboBox1.getParent();
        panelControles.setBackground(azulOscuro);

        // 2. ARREGLAR TEXTOS
        Color blanco = Color.WHITE;
        jLabel1.setForeground(blanco); 
        jLabel2.setForeground(blanco); 
        jLabel3.setForeground(blanco); 
        jLabel4.setForeground(blanco); 
        jLabel5.setForeground(blanco); 
        jLabel6.setForeground(blanco); 
        jLabel7.setForeground(blanco); 

        jCheckBox1.setBackground(azulOscuro);
        jCheckBox1.setForeground(blanco);
        jCheckBox1.setFocusPainted(false); 
        jCheckBox2.setBackground(azulOscuro);
        jCheckBox2.setForeground(blanco);
        jCheckBox2.setFocusPainted(false);

        Color verde = new Color(46, 204, 113);
        Color rojo  = new Color(231, 76, 60);
        Color azul  = new Color(52, 152, 219);
        Color gris  = new Color(149, 165, 166);

        estiloBoton(jButton6, rojo);
        estiloBoton(jButton5, verde);
        estiloBoton(jButton4, azul);
        estiloBoton(jButton3, azul);
        estiloBoton(jButton2, rojo);
        estiloBoton(jButton1, gris);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(189, 195, 199), 1));
        
        // sera?
        // a ver a verrr
        vertices = new ArrayList(); 
        grafoM = new GrafoMatriz(100);
        f = new Visualizador(vertices,grafoM);
        f.setAlAgregar(()->{
            actualizarArcos();
            actualizarVertices();
        });
        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanel1.add(f);
        jPanel1.validate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jCheckBox1 = new javax.swing.JCheckBox();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jCheckBox2 = new javax.swing.JCheckBox();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setPreferredSize(new java.awt.Dimension(650, 304));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 644, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel1.setText("Arcos");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No dirigido", "Dirigido" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        jLabel2.setText("Opciones");

        jCheckBox1.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jCheckBox1.setText("Valorado");
        jCheckBox1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "." }));

        jButton1.setText("Cambiar peso");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel3.setText("Tipo de grafo ");

        jButton2.setText("Borrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Componentes conexas");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel4.setText("Funciones");

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel5.setText("Recorridos");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "." }));

        jLabel6.setText("Nodo origen");

        jLabel7.setText("Recorrido");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Anchura", "Profundidad" }));

        jButton4.setText("Recorrer");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Dijkstra");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jCheckBox2.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jCheckBox2.setText("Espacio");
        jCheckBox2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jButton6.setText("Limpiar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(286, 286, 286))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jButton6)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jButton4)))
                        .addGap(228, 228, 228))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel5))
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jButton3)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jButton5)))
                        .addGap(23, 23, 23))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 9, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jButton2)
                        .addGap(12, 12, 12)
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton3)
                                        .addGap(11, 11, 11)
                                        .addComponent(jButton5))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                                        .addComponent(jLabel7)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(40, 40, 40)
                                        .addComponent(jCheckBox1)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton6)))
                        .addContainerGap(12, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
         
    }//GEN-LAST:event_jPanel1MouseEntered

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
         ArrayList<ArcoPanel> arcos = f.getArcos();
         for(ArcoPanel e:arcos){
                    jComboBox2.addItem(e.getInicio().toString()+" "+e.getFin().toString());
        }
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        if(evt.getStateChange()==java.awt.event.ItemEvent.SELECTED){
            String tipo = jComboBox1.getSelectedItem().toString();
            System.out.println("Tipo "+tipo);
            boolean flag = tipo.equals("No dirigido");
            f.setDirigido(!flag);
            f.revalidate();
            f.repaint();
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
            f.setValorado(jCheckBox1.isSelected());
            System.out.println("Valorado?: "+jCheckBox1.isSelected());
            f.revalidate();
            f.repaint();
            
            jComboBox2.removeAllItems();
            ArrayList<ArcoPanel> arcos = f.getArcos();
            for(ArcoPanel e:arcos){
                jComboBox2.addItem(e);
            }

            if(jCheckBox1.isSelected()){
                jButton1.setEnabled(true);                
            } else {
                jButton1.setEnabled(false);                
            }
            
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ArcoPanel e = (ArcoPanel)jComboBox2.getSelectedItem();        
        
        int peso = Integer.parseInt(JOptionPane.showInputDialog("Ingresa el nuevo peso del arco: "+e,e.getPeso()));
        e.setPeso(peso);
        f.repaint();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(jComboBox2.getSelectedItem()!=null){
            ArcoPanel e = (ArcoPanel)jComboBox2.getSelectedItem();
            f.eliminarArco(e);
            actualizarArcos();
            System.out.println("Arco borrado");
        } else {
            JOptionPane.showMessageDialog(null, "Debes seleccionar un arco");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       f.pintarCompConexas();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String tipoRecorrido = jComboBox4.getSelectedItem().toString();
        String nodoOrigen = jComboBox3.getSelectedItem().toString();

        ArrayList<String> r = null; 

        try {
            switch(tipoRecorrido){
                case "Anchura" -> r = f.grafo.getAnchura(nodoOrigen);
                case "Profundidad" -> r = f.grafo.getProfundidad(nodoOrigen);
            }

            if (r != null) {
                String camino = "";
                for(String nodo : r) {
                    camino += nodo + " -> ";
                }
                camino += "FIN";

                System.out.println(camino);
                JOptionPane.showMessageDialog(null, camino);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
 try {//inicia Dijkstra
        if (jComboBox3.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Selecciona un vertice origen primero");
            return;
        }
        
        if (!jCheckBox1.isSelected()) {
            JOptionPane.showMessageDialog(this, 
                "El grafo debe estar marcado como 'Valorado' para usar Dijkstra");
            return;
        }
        
        VerticePanel origen = (VerticePanel) jComboBox3.getSelectedItem();
        
        GrafoAdcia grafo = crearGrafoDesdeVisualizacion();
        
        ResultadoDijkstra resultado = Dijkstra.dijkstra(grafo, origen.getNombre());
        
        mostrarTodosLosCaminos(resultado, origen.getNombre());
        
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error en Dijkstra: " + ex.getMessage());
        ex.printStackTrace();
    }
} 

private void mostrarTodosLosCaminos(ResultadoDijkstra resultado, String origen) {
    try {
        StringBuilder sb = new StringBuilder();
        sb.append("Dijkstra : Camino desde  '").append(origen).append("' \n\n");
        
        boolean hayCaminos = false;
        
        for (VerticePanel v : f.getVertices()) {
            String destino = v.getNombre();
            
            if (destino.equals(origen)) continue;
            
            double distancia = resultado.getDistancia(destino);
            List<String> camino = resultado.getCamino(destino);
            
            if (distancia != Double.MAX_VALUE) {
                hayCaminos = true;
                sb.append("Hacia '").append(destino).append("':\n");
                sb.append("  Distancia: ").append(String.format("%.1f", distancia)).append("\n");
                sb.append("  Camino: ").append(camino).append("\n\n");
            }
        }
        
        if (!hayCaminos) {
            sb.append("No hay caminos hacia otros vértices desde '").append(origen).append("'");
        }
        
        JTextArea textArea = new JTextArea(sb.toString());
        textArea.setEditable(false);
        textArea.setFont(new java.awt.Font("Monospaced", java.awt.Font.PLAIN, 12));
        JScrollPane scrollPane = new JScrollPane(textArea);
        scrollPane.setPreferredSize(new java.awt.Dimension(500, 400));
        
        JOptionPane.showMessageDialog(this, scrollPane, 
            "Dijkstra - Caminos desde " + origen, JOptionPane.INFORMATION_MESSAGE);
        
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
    }    }//GEN-LAST:event_jButton5ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        f.setModoEspecial(jCheckBox2.isSelected());
        f.revalidate();
        f.repaint();
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        f.grafo.limpiarGrafo();
        f.vertices.clear();
        f.arcos.clear();
        f.repaint();
        f.revalidate();
        actualizarArcos();
        actualizarVertices();
    }//GEN-LAST:event_jButton6ActionPerformed

    private GrafoAdcia crearGrafoDesdeVisualizacion() throws Exception {
    GrafoAdcia grafo = new GrafoAdcia(100);
    
    for (VerticePanel v : f.getVertices()) {
        grafo.nuevoVertice(v.getNombre());
    }
    
    for (ArcoPanel arco : f.getArcos()) {
        String nombreOrigen = arco.getInicio().getNombre();
        String nombreDestino = arco.getFin().getNombre();
        double peso = arco.getPeso();
        
        grafo.nuevaArista(nombreOrigen, nombreDestino, peso);
        
        if (jComboBox1.getSelectedItem().equals("No dirigido")) {
            grafo.nuevaArista(nombreDestino, nombreOrigen, peso);
        }
    }
    
    return grafo;
}

    private void mostrarResultadoDijkstraSimple(ResultadoDijkstra resultado, String origen, String destino) {
        try {
            if (!Dijkstra.esAlcanzable(resultado, destino)) {
                JOptionPane.showMessageDialog(this, 
                    "El vértice '" + destino + "' no es alcanzable desde '" + origen + "'");
                return;
            }

            List<String> camino = resultado.getCamino(destino);
            double distancia = resultado.getDistancia(destino);
            StringBuilder mensaje = new StringBuilder();
            mensaje.append("Dijkstra o camino mas corto\n\n");
            mensaje.append("Origen: ").append(origen).append("\n");
            mensaje.append("Destino: ").append(destino).append("\n");
            mensaje.append("Distancia total: ").append(String.format("%.1f", distancia)).append("\n");
            mensaje.append("Camino: ").append(camino).append("\n\n");

            mensaje.append("Detalles del camino:\n");
            for (int i = 0; i < camino.size(); i++) {
                mensaje.append("Paso ").append(i).append(": ").append(camino.get(i));
                if (i < camino.size() - 1) {
                    mensaje.append(" → ");
                }
            }

            JTextArea textArea = new JTextArea(mensaje.toString());
            textArea.setEditable(false);
            textArea.setFont(new java.awt.Font("Monospaced", java.awt.Font.PLAIN, 12));
            JScrollPane scrollPane = new JScrollPane(textArea);
            scrollPane.setPreferredSize(new java.awt.Dimension(400, 300));

            JOptionPane.showMessageDialog(this, scrollPane, 
                "Resultado Dijkstra", JOptionPane.INFORMATION_MESSAGE);

            System.out.println("Dikstra camino mas corto");
            System.out.println(mensaje.toString());

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error mostrando resultados: " + ex.getMessage());
        }
    }           //termina  dijkstra
    
    private void actualizarArcos(){
        jComboBox2.removeAllItems();
   
            ArrayList<ArcoPanel> edgs = f.getArcos();
            for(ArcoPanel e:edgs){
                jComboBox2.addItem(e);
            }
    
    }
    
    private void actualizarVertices(){
        jComboBox3.removeAllItems();
        ArrayList<VerticePanel> v = f.getVertices();
        for(VerticePanel u:v){
            jComboBox3.addItem(u);
        }
    }
    
    private void estiloBoton(javax.swing.JButton btn, Color colorFondo) {
        btn.setBackground(colorFondo);
        btn.setForeground(Color.BLACK); // Texto blanco
        btn.setFocusPainted(false);     // Quita el recuadro azul al hacer clic
        btn.setBorderPainted(false);    // QUITA EL BORDE 3D (Clave del flat design)
        btn.setFont(new Font("Yu Gothic UI", Font.BOLD, 12));
        // Cambia el cursor a manita
        btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<Object> jComboBox2;
    private javax.swing.JComboBox<Object> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
