/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Programas;

import Grafos.ArcoPanel;
import Grafos.GrafoMatriz;
import Grafos.VerticePanel;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Point;
import java.awt.RenderingHints;
import java.awt.Stroke;
import java.awt.event.MouseEvent;
import java.awt.geom.AffineTransform;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author crist
 */
public class Visualizador extends javax.swing.JPanel {

    /**
     * Creates new form Visualizador
     */
    
    ArrayList<VerticePanel> vertices;
    boolean click = false;
    boolean dirigido = false;
    boolean valorado = false;
    final int DIAMETRO = 40;
    final int RADIO = DIAMETRO/2;
    private Runnable alAgregarArco;
    ArrayList<ArcoPanel> arcos;
    VerticePanel primero;
    VerticePanel nodoMoviendo=null;//:p
    GrafoMatriz grafo;
    ArrayList<Point> estrellitas=new ArrayList();
    boolean modoEspecial;
    // Muy interesante la clase Point!
    // https://docs.oracle.com/javase/8/docs/api/java/awt/Point.html
    
    public Visualizador(ArrayList<VerticePanel> v,GrafoMatriz g) {
        initComponents();
        vertices = v;
        arcos = new ArrayList();
        grafo = g;
//        SsetPreferredSize(new Dimension(650,300));
        this.setBackground(Color.WHITE);
        
        // Detectar click! con mouseListenter
        // guia: https://docs.oracle.com/javase/8/docs/api/java/awt/event/MouseListener.html
        this.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent evt){
                nodoMoviendo = ClickDentro(evt.getX(), evt.getY());
                
                if(nodoMoviendo!=null){
                    System.out.println("Agarrando: "+nodoMoviendo.getNombre());
                }
            }
            @Override
            public void mouseReleased(MouseEvent evt){
                nodoMoviendo=null;
                System.out.println("dejando ir...");
            }
        });
        
        // La diferencia entre MouseAdapter y MouseMotionAdapter es que uno "escucha" (listen) clicks y el otro
        // el desplazamiento del mouse!
        
        // guia: https://docs.oracle.com/javase/8/docs/api/java/awt/event/MouseMotionListener.html
        this.addMouseMotionListener(new java.awt.event.MouseMotionAdapter(){
            @Override
            public void mouseDragged(MouseEvent evt){
                if(nodoMoviendo!=null){
                    nodoMoviendo.setX(evt.getX());
                    nodoMoviendo.setY(evt.getY());
                    repaint();
                }
            }
        });
        
        // generar 100 estrellas al azaar
        for(int i=0; i<100; i++){
            int x = (int)(Math.random() * 800);
            int y = (int)(Math.random() * 600);
            estrellitas.add(new Point(x, y));
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2d = (Graphics2D)g;
        System.out.println("Dirigod: "+dirigido);
        g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON); // suavizar lineas
        g2d.setRenderingHint(RenderingHints.KEY_TEXT_ANTIALIASING, RenderingHints.VALUE_TEXT_ANTIALIAS_ON); // suavizar texto
        
        Font fuenteBonita = new Font("Segoe UI", Font.BOLD ,14); 
        Font fuentePeso = new Font("Segoe UI", Font.BOLD ,18); 
        
        if(modoEspecial){
            g2d.setColor(Color.BLACK);
            g2d.fillRect(0, 0, getWidth(), getHeight());
            
            g2d.setColor(Color.WHITE);
            for(Point p:estrellitas){
                g2d.fillOval(p.x, p.y, 2, 2); // 2x2 pixeles, cada puntitio
            }
        } else {
            // Fondo Blanco Normal
            g2d.setColor(Color.WHITE);
            g2d.fillRect(0, 0, getWidth(), getHeight());
        }
        
        for(ArcoPanel e: arcos){
            int Ix = e.getInicio().getX();
            int Iy = e.getInicio().getY();
            
            int Fx = e.getFin().getX();
            int Fy = e.getFin().getY();
            
            if(modoEspecial) g2d.setColor(Color.LIGHT_GRAY);
            else {
                if(valorado) g2d.setColor(Color.GRAY);
                else g2d.setColor(Color.BLACK);
            }
            
            g2d.setStroke(new BasicStroke(2));
            
            g2d.drawLine(Ix,Iy,Fx,Fy);
            
            // tan tan tann, ahora, y si es bucle?
            if(Ix==Fx && Iy==Fy){
                g2d.setColor(Color.ORANGE);
                g2d.drawOval(Ix-23,Iy-23, RADIO,RADIO);
                g2d.setColor(Color.BLACK);
                //yep
            }
        }
        
        g2d.setColor(Color.BLACK);
        
        
        for(VerticePanel u : vertices){
            int r = RADIO;  
            int cx = u.getX();        
            int cy = u.getY();        
            
            int dx = cx - r;       
            int dy = cy - r;
            
            if(modoEspecial){
                
                Color colorNodo = u.getColor();
                if(colorNodo.equals(Color.WHITE)) colorNodo = new Color(100, 100, 150); 

                //Gradiente: Foco de luz en la esquina superior izquierda 
                java.awt.RadialGradientPaint planeta = new java.awt.RadialGradientPaint(
                    new java.awt.geom.Point2D.Float(dx + 10, dy + 10),  // empieza el blanco, Pto luz esquina superior izq
                    DIAMETRO, // que tan lejos llegara el degradado?-> Hasta el diametro
                    new float[] { 0.0f, 1.0f }, // porcentajes de distancia desde el foco de luz!
                        // de 0 a 100%
                    new Color[] { Color.WHITE, colorNodo } // el color va desde blanco hasta el color del nodo!
                );
                // https://docs.oracle.com/javase/8/docs/api/java/awt/RadialGradientPaint.html
                // :p, interesantisimo!
                
                g2d.setPaint(planeta);
                g2d.fillOval(dx, dy, DIAMETRO, DIAMETRO);
                
                g2d.setColor(new Color(255, 255, 255, 50));
                g2d.setStroke(new BasicStroke(1));
                g2d.drawOval(dx, dy, DIAMETRO, DIAMETRO);

                g2d.setFont(new Font("Segoe UI", Font.BOLD, 14));
                g2d.setColor(Color.BLACK); 
                g2d.drawString(u.getNombre(), cx - 3, cy + 5);
                g2d.setColor(Color.WHITE);
                g2d.drawString(u.getNombre(), cx - 4, cy + 4);
                
            } else {
                g2d.setColor(u.getColor());
                g2d.fillOval(dx, dy, DIAMETRO, DIAMETRO);

                g2d.setColor(Color.BLACK);
                g2d.setStroke(new BasicStroke(2));
                g2d.drawOval(dx, dy, DIAMETRO, DIAMETRO);

                g2d.setFont(fuenteBonita);
                g2d.setColor(Color.BLUE);
                
                g2d.drawString(u.getNombre(), cx - 4, cy + 4);
            }
        }
        
        if(dirigido){
            for(ArcoPanel e: arcos){
                int x1 = e.getInicio().getX();
                int y1 = e.getInicio().getY();
                int x2 = e.getFin().getX();
                int y2 = e.getFin().getY();
                
                if(x1!=x2&&y1!=y2){
                // inclinacion de nodo origen a nodo destino
                double angulo = Math.atan2(y2 - y1, x2 - x1);

                // Pos original
                AffineTransform transformacionOriginal = g2d.getTransform();

                // Movernos a nodo destino
                g2d.translate(x2, y2);  // Mover ORIGEN al NODO destino
                // El origen ya no esta en (0,0), ahora esta en (x2,y2) :)
                g2d.rotate(angulo - Math.PI / 2); // giramos hacia ARRIBA, por eso le restamos 90 grados

                int[] xPuntos = {0, -10, 10}; 
                int[] yPuntos = {-(RADIO), -35, -35};
                
                // (0,RADIO) borde del vertice
                // (-10,-35) y (10,35) base triangulo
                
                g2d.fillPolygon(xPuntos, yPuntos, 3);

                // restauramos
                g2d.setTransform(transformacionOriginal);
                }
            }
        }
        
        if(valorado){
            for(ArcoPanel e:arcos){
                int Ix = e.getInicio().getX();
                int Iy = e.getInicio().getY();

                int Fx = e.getFin().getX();
                int Fy = e.getFin().getY();
                // www.youtube.com/watch?v=Lro3Sk4M21s&t=502
                // gracias profe alex
                g2d.setColor(Color.MAGENTA);
                g2d.setFont(fuentePeso);
                String peso;
                if(e.getPeso()==100000000) peso = "x";
                else peso = Integer.toString(e.getPeso());
                g2d.drawString(peso, ((Ix+Fx)/2), ((Iy+Fy)/2));
            }
        }
    }
    
    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        
        // Mejoras 
        // CAMBIAR A SWTICH! (mas entendible)
        
        int x = evt.getX();
        int y = evt.getY();
        
        System.out.println("Click!");
        
        if(evt.getButton()==MouseEvent.BUTTON1){ // Click izuquierdo
            System.out.println("Click izq");
            String s = JOptionPane.showInputDialog("Ingresa el valor del vertice: ");
            VerticePanel u = new VerticePanel(x, y, s);
            vertices.add(u);
            grafo.nuevoVertice(s);
            repaint();
            grafo.mostrarMatriz();
            if(alAgregarArco!=null){
                alAgregarArco.run();
            }

        } else if(evt.getButton()==MouseEvent.BUTTON3){ // Click derecho:)
            VerticePanel u = ClickDentro(x,y);
            int peso = 100000000;
            if(u!=null){
                if(primero==null){
                    primero = u;
                    System.out.println("Primero: "+u.getNombre());
                }else {
                    // Se selecciona otro nodo
                    System.out.println("Segundo " +u.getNombre());
                    ArcoPanel e; // e = edge:)
                    if(!valorado){
                        e = new ArcoPanel(primero,u);
                        
                        try {
                            grafo.nuevoArco(primero.getNombre(), u.getNombre());
                        } catch (Exception ex) {
                            Logger.getLogger(Visualizador.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        
                        
                    }else{
                        peso = Integer.parseInt(JOptionPane.showInputDialog("Peso: "));
                        e = new ArcoPanel(primero,u,peso);
                        
                        try {
                            grafo.nuevoArco(primero.getNombre(), u.getNombre(), peso);
                        } catch (Exception ex) {
                            Logger.getLogger(Visualizador.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        
                    }
                    arcos.add(e);
                    grafo.mostrarMatriz();
                    primero = null;
                    repaint();
                    
                    if(alAgregarArco!=null){
                        alAgregarArco.run();
                    }
                }
            } else {
                // no dimos click dentro de un nodo
                primero = null;
            }
        }
    }//GEN-LAST:event_formMouseClicked

    private VerticePanel ClickDentro(int x,int y){
        int r = DIAMETRO/2;
        
        // Recorremos todos los vertices para saber si estamos dentro de un nodo
        for(VerticePanel u: vertices){
            double dist = Math.sqrt(Math.pow((x-u.getX()),2)+Math.pow((y-u.getY()),2));
            if(dist<=r){
                return u;
            }
        }
        return null;
    }
    
    public void pintarCompConexas() {
        int[] grupos = grafo.encontrarComponentes();
        
        // generar colores aleatorios, segun la cantidad de vertices!
        // asi que habra para todos jeje
        Color[] paleta = new Color[vertices.size()];
        for(int i=0; i<paleta.length; i++){
            // Generamos un color pastel aleatorio para que se vea bonito
            float r = (float)(Math.random() / 2f + 0.5f);
            float g = (float)(Math.random() / 2f + 0.5f);
            float b = (float)(Math.random() / 2f + 0.5f);
            paleta[i] = new Color(r, g, b);
        }

        // Asignamos los colores a los paneles
        // OJO, aca asumimos que el orden de los vertices coincide con los índices de la matriz 0,1,2...
        for(int i=0; i<vertices.size(); i++){
            int idGrupo = grupos[i];
            if(idGrupo >= 0){
                vertices.get(i).setColor(paleta[idGrupo]);
            }
        }
        repaint();
    }
    
    public boolean isDirigido() {
        return dirigido;
    }

    public void setDirigido(boolean dirigido) {
        this.dirigido = dirigido;
    }

    public boolean isValorado() {
        return valorado;
    }

    public void setValorado(boolean valorado) {
        this.valorado = valorado;
    }

    public ArrayList<ArcoPanel> getArcos() {
        return arcos;
    }
    
    public ArrayList<VerticePanel> getVertices(){
        return vertices;
    }
    
    public void setAlAgregar(Runnable alAgregar) {
        this.alAgregarArco = alAgregar;
        
    }
    
    public void eliminarArco(ArcoPanel e){
        arcos.remove(e);
        repaint();
    }

    public boolean isModoEspecial() {
        return modoEspecial;
    }

    public void setModoEspecial(boolean modoEspecial) {
        this.modoEspecial = modoEspecial;
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
