/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Programas;

import Grafos.ArcoPanel;
import Grafos.VerticePanel;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.Stroke;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author crist
 */
public class Visualizador extends javax.swing.JPanel {

    /**
     * Creates new form Visualizador
     */
    
    ArrayList<VerticePanel> vertices;
    boolean click = false;
    boolean dirigido = false;
    boolean valorado = false;
    final int DIAMETRO = 40;
    final int RADIO = DIAMETRO/2;
    ArrayList<ArcoPanel> arcos;
    VerticePanel primero;
    
    public Visualizador(ArrayList<VerticePanel> v) {
        initComponents();
        vertices = v;
        arcos = new ArrayList();
        setPreferredSize(new Dimension(618,300));
        this.setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2d = (Graphics2D)g;
        System.out.println("Dirigod: "+dirigido);
        g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON); // suavizar lineas
        g2d.setRenderingHint(RenderingHints.KEY_TEXT_ANTIALIASING, RenderingHints.VALUE_TEXT_ANTIALIAS_ON); // suavizar texto
        
        Font fuenteBonita = new Font("Segoe UI", Font.BOLD ,14); 
        Font fuentePeso = new Font("Segoe UI", Font.ITALIC ,18); 
        
        for(ArcoPanel e: arcos){
            int Ix = e.getInicio().getX();
            int Iy = e.getInicio().getY();
            
            int Fx = e.getFin().getX();
            int Fy = e.getFin().getY();
            g2d.setStroke(new BasicStroke(2));
            
            if(valorado) g2d.setColor(Color.GRAY);
            g2d.drawLine(Ix,Iy,Fx,Fy);
        }
        
        g2d.setColor(Color.BLACK);
        
        for(VerticePanel u:vertices){
            int x = u.getX();
            int y = u.getY();
            int r= DIAMETRO/2;
            
            g2d.setColor(Color.WHITE);
            g2d.fillOval(x-r, y-r, DIAMETRO, DIAMETRO);

            g2d.setColor(Color.BLACK);
            g2d.setStroke(new BasicStroke(2));
            g2d.drawOval(x-r, y-r, DIAMETRO, DIAMETRO);
            
            g2d.setFont(fuenteBonita);
            g2d.setColor(Color.BLUE);
            g2d.drawString(u.getNombre(), x-4, y+4);
            
        }
        
        if(dirigido){
            for(ArcoPanel e: arcos){
                int Fx = e.getFin().getX();
                int Fy = e.getFin().getY();
                
                System.out.println("Dibujando circulito");
                g2d.setColor(Color.red);
                g2d.setStroke(new BasicStroke(3));
                g2d.drawOval(Fx, Fy, 10, 10);

            }
        }
        
        if(valorado){
            for(ArcoPanel e:arcos){
                int Ix = e.getInicio().getX();
                int Iy = e.getInicio().getY();

                int Fx = e.getFin().getX();
                int Fy = e.getFin().getY();
                // www.youtube.com/watch?v=Lro3Sk4M21s&t=502
                // gracias profe alex
                g2d.setColor(Color.RED);
                g2d.setFont(fuentePeso);
                String peso;
                if(e.getPeso()==100000000) peso = "x";
                else peso = Integer.toString(e.getPeso());
                g2d.drawString(peso, ((Ix+Fx)/2), ((Iy+Fy)/2));
            }
        }
    }
    
    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        
        // Mejoras 
        // CAMBIAR A SWTICH! (mas entendible)
        
        int x = evt.getX();
        int y = evt.getY();
        
        System.out.println("Click!");
        
        if(evt.getButton()==MouseEvent.BUTTON1){ // Click izuquierdo
            System.out.println("Click izq");
            String s = JOptionPane.showInputDialog("Ingresa el valor del vertice: ");
            VerticePanel u = new VerticePanel(x, y, s);
            vertices.add(u);
            repaint();
        } else if(evt.getButton()==MouseEvent.BUTTON3){ // Click derecho:)
            VerticePanel u = ClickDentro(x,y);
            if(u!=null){
                if(primero==null){
                    primero = u;
                    System.out.println("Primero: "+u.getNombre());
                }else {
                    // Se selecciona otro nodo
                    System.out.println("Segundo " +u.getNombre());
                    ArcoPanel e;
                    if(!valorado) e = new ArcoPanel(primero,u); // e = edge:)
                    else{
                        int peso = Integer.parseInt(JOptionPane.showInputDialog("Peso: "));
                        e = new ArcoPanel(primero,u,peso);
                    }
                    arcos.add(e);
                    
                    primero = null;
                    
                    repaint();
                }
            } else {
                // no dimos click dentro de un nodo
                primero = null;
            }
        }
    }//GEN-LAST:event_formMouseClicked

    private VerticePanel ClickDentro(int x,int y){
        int r = DIAMETRO/2;
        
        // Recorremos todos los vertices para saber si estamos dentro de un nodo
        for(VerticePanel u: vertices){
            double dist = Math.sqrt(Math.pow((x-u.getX()),2)+Math.pow((y-u.getY()),2));
            if(dist<=r){
                return u;
            }
        }
        return null;
    }
    
    
    
    public boolean isDirigido() {
        return dirigido;
    }

    public void setDirigido(boolean dirigido) {
        this.dirigido = dirigido;
    }

    public boolean isValorado() {
        return valorado;
    }

    public void setValorado(boolean valorado) {
        this.valorado = valorado;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
